version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:management # Use the management image
    ports:
      - "5672:5672"   # RabbitMQ AMQP protocol
      - "15672:15672"  # RabbitMQ Management Web UI
    networks:
      - microservice_demo
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  microservice_demo:
    driver: bridge